### ISSUE TITLE
Feature labels in AdditiveForceVisualzer

### ISSUE THREAD

**Issue by ytsaig** [interpretable-ml/iml#2]
Thanks for putting together SHAP and the associated visualization tools, really well done!

Question: would it be easy to add tooltips with the feature names (and associated values) when hovering over individual elements in the single AdditiveForceVisualizer? Right now the labels for the top few features are displayed below the bars, but with many features it'd be useful to know what are other features that contribute to an individual prediction. My javascript is pretty weak, so can't tell if it's easy to do.

**Comment by slundberg** [comment]
great idea! I'll leave this issue open as a tag to do that. It should not
be very hard.
